### ISSUE TITLE
Next Js dynamic routing implementation

### ISSUE THREAD

**Issue by sb-saksham** [JulianNicholls/Blockchain-Course#20]
I was skimming through NextJs documentation then I saw that Next do support [Dynamic routing](https://nextjs.org/docs/routing/dynamic-routes) but I was not able to work my way through on how to implement it with Class based Component. could you help me out??
Help will be really appreciated. Thanks!

**Comment by JulianNicholls** [comment]
This is not relevant to this repository. I don't really know anything about Next.
